#IMPLEMENTAÇÃO DE ENQUEUE E DEQUEUE

fila = [10,20,30,40,50]

print(fila)

deq = fila.pop(0) #DEQUEUE - ARMAZENANDO O QUE FOI TIRADO DA ESTRUTURA EM UMA VARIÁVEL

fila.append(deq) #ENQUEUE - ADICIONOU O VALOR RETIRADO NO FIM DA FILA
print(fila)
